# Generated by Django 3.2.13 on 2022-10-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='acces',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='types',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
