# Generated by Django 3.2.13 on 2022-10-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20221019_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='accept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('types', models.CharField(max_length=400, null=True)),
                ('acces', models.CharField(max_length=400, null=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
