# Generated by Django 3.2.13 on 2022-10-24 19:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='box',
        ),
    ]
