# Generated by Django 3.2.13 on 2022-10-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_posts_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
