# Generated by Django 3.2.13 on 2022-10-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_box_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='img',
            field=models.CharField(max_length=500000000000, null=True),
        ),
    ]
