# Generated by Django 3.2.13 on 2022-11-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_box_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
